seml:
  executable: run.py
  name: Active_Learning
  output_dir: seml/logs
  project_root_dir: ../../..

slurm:
  experiments_per_job: 1
  max_simultaneous_jobs: 4  # Restrict number of simultaneously running jobs per job array
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 2  # num cores
    time: 2-00:00     # max time, D-HH:MM

###### BEGIN PARAMETER CONFIGURATION ######

grid:
  config.1:
    type: choice
    options:
      - ["models/sbm/mcd_ppnp"]
      - ["models/sbm/mcd_gcn"]
      - ["models/sbm/ppnp"]
      - ["models/sbm/gcn"]
  config.2:
    type: choice
    options:
      - ["modes/sbm_al/active_learning"]
  config.3:
    type: choice
    options:
      - ["active_learning/l2_distance"]
      - ["active_learning/random"]
      - ["active_learning/uncertainty_isolated_aleatoric"]
      - ["active_learning/uncertainty_propagated_aleatoric"]
  overrides.tags:
    type: choice
    options:
      - ['active_learning_sbmal_v4']

# EPISTEMIC

grid:
  config.1:
    type: choice
    options:
      - ["models/sbm/mcd_ppnp"]
      - ["models/sbm/mcd_gcn"]
  config.2:
    type: choice
    options:
      - ["modes/sbm_al/active_learning"]
  config.3:
    type: choice
    options:
      - ["active_learning/uncertainty_isolated_epistemic"]
      - ["active_learning/uncertainty_propagated_epistemic"]
  overrides.tags:
    type: choice
    options:
      - ['active_learning_sbmal_v4']

# BASELINES

grid:
  config.1:
    type: choice
    options:
      - ["models/sbm/ppnp"]
      - ["models/sbm/mcd_ppnp"]
      - ["models/sbm/gcn"]
      - ["models/sbm/mcd_gcn"]
  config.2:
    type: choice
    options:
      - ["active_learning/random"]
      - ["active_learning/fixed_all"]
      - ["active_learning/fixed_ic"]
      - ["active_learning/fixed_ie"]
      - ["active_learning/fixed_uc"]
      - ["active_learning/fixed_ue"]
  config.3:
    type: choice
    options:
      - ["modes/sbm_al/active_learning_baseline"]
  overrides.tags:
    type: choice
    options:
      - ['active_learning_sbmal_v4']