seml:
  executable: run.py
  name: Active_Learning
  output_dir: seml/logs
  project_root_dir: ../..

slurm:
  experiments_per_job: 1
  max_simultaneous_jobs: 4  # Restrict number of simultaneously running jobs per job array
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 2  # num cores
    time: 2-00:00     # max time, D-HH:MM

###### BEGIN PARAMETER CONFIGURATION ######

grid:
  config:
    type: choice
    options:
      - ["models/ppnp", "modes/sbm/train/classification_7"]
      - ["models/mcd_ppnp", "modes/sbm/train/classification_7"]
      - ["models/gcn", "modes/sbm/train/classification_7"]
      - ["models/mcd_gcn", "modes/sbm/train/classification_7"]
  overrides.training.learning_rate.TRAINING:
    type: choice
    options:
      - 0.1
      - 0.03
      - 0.01
      - 0.003
  overrides.training.reg_lambda.TRAINING:
    type: choice
    options:
      - 0.0
      - 0.001
      - 0.0003
      - 0.0001
  overrides.training.drop_prob:
    type: choice
    options:
      - 0.0
      - 0.25
      - 0.5
      - 0.75