experiment:
  active_learning_selector: FIXED_UNBALANCED
  active_learning_training_type: null
  active_learning_selector_network_mode: PROPAGATED
  active_learning_selector_uncertainty_mode: ALEATORIC