custom_name: classification
tags: ['active_learning_sbm_al_v1']

experiment:

  seeds:
    end: 10
  iterations_per_seed: 3

  dataset: GENERATED_SBM_AL
  datapoints_training_per_class: 2
  datapoints_stopping: 300
  datapoints_known: 1500
  num_classes: 6
  sbm_classes: [10, 100, 10, 100, 10, 100, 10, 100,10, 100, 10, 100,10, 100, 10, 100,10, 100, 10, 100,10, 100, 10, 100,10, 100, 10, 100]
  sbm_connection_probabilities_id_in_cluster: 0.01
  sbm_connection_probabilities_id_out_cluster: 0.002
  
  sbm_nfeatures: 10
  sbm_feature_mean: 0
  sbm_feature_variance: 1
  sbm_feature_sampling_variance: 30
  sbm_feature_sampling_variance_informed: 3

  active_learning: False
  active_learning_start_cap_per_class: 3
  active_learning_update_interval: 50
  active_learning_budget_per_update: 4
  active_learning_budget: 60
  active_learning_starting_class: [0,1,2,3,4,5,6]
  active_learning_selector: FIXED
  active_learning_selector_network_mode: ISOLATED
  active_learning_selector_uncertainty_mode: ALEATORIC
  active_learning_l2_distance_logging: True

  ood: NONE
  
training:
  ood_eval_during_training: False
  patience: 
    TRAINING: 200
  max_epochs:
    TRAINING: 200