custom_name: classification
tags: ['active_learning_sbm_al_v1']

experiment:

  seeds:
    end: 10
  iterations_per_seed: 3

  dataset: GENERATED_SBM_AL
  datapoints_training_per_class: 100
  datapoints_stopping: 300
  datapoints_known: 1500
  num_classes: 6
  sbm_classes: [100, 100, 100, 100, 100, 100, 100, 100,100, 100, 100, 100,100, 100, 100, 100,100, 100, 100, 100,100, 100, 100, 100,100, 100, 100, 100]
  sbm_connection_probabilities_id_in_cluster: 0.01
  sbm_connection_probabilities_id_out_cluster: 0.002
  
  sbm_nfeatures: 10
  sbm_feature_mean: 0
  sbm_feature_variance: 1
  sbm_feature_sampling_variance: 10
  sbm_feature_sampling_variance_informed: 0.1

  active_learning: True
  active_learning_start_cap_per_class: 1
  active_learning_update_interval: 200
  active_learning_budget_per_update: 2
  active_learning_budget: 21
  active_learning_starting_class: [0,1,2,3,4,5,6]
  active_learning_selector: UNCERTAINTY
  active_learning_selector_network_mode: ISOLATED
  active_learning_selector_uncertainty_mode: ALEATORIC
  active_learning_l2_distance_logging: True

  ood: NONE
  
training:
  ood_eval_during_training: False
  patience: 
    TRAINING: 2600
  max_epochs:
    TRAINING: 2600