custom_name: active_learning
experiment:

  seeds:
    end: 10
  iterations_per_seed: 3

  dataset: GENERATED_SBM
  datapoints_training_per_class: 20
  datapoints_stopping: 200
  datapoints_known: 1500
  sbm_classes: [600, 600, 600, 600]
  sbm_connection_probabilities_id_in_cluster: 0.01
  sbm_connection_probabilities_id_out_cluster: 0.0002
  sbm_connection_probabilities_ood_in_cluster: 0.
  sbm_connection_probabilities_ood_out_cluster: 0.002
  
  sbm_nfeatures: 10
  sbm_feature_mean: 0
  sbm_feature_variance: 1
  sbm_feature_sampling_variance: 30
  
  active_learning: True
  active_learning_update_interval: 100
  active_learning_budget_per_update: 4
  active_learning_budget: 20
  active_learning_starting_class: [0]
  active_learning_selector: UNCERTAINTY
  active_learning_selector_network_mode: PROPAGATED
  active_learning_selector_uncertainty_mode: ALEATORIC

  ood: NONE
  
training:
  ood_eval_during_training: False
  early_stopping: 
    TRAINING: False