custom_name: ood_loc
experiment:

  seeds:
    end: 10
  iterations_per_seed: 3

  dataset: GENERATED_SBM
  datapoints_training_per_class: 20
  datapoints_stopping: 200
  datapoints_known: 1500
  sbm_classes: [600, 600, 600, 600]
  sbm_connection_probabilities: [
    [0.01, 0.001, 0.001, 0.0], 
    [0.001, 0.01, 0.0, 0.0], 
    [0.001, 0.0, 0.01, 0.001], 
    [0.0, 0.0, 0.001, 0.01]
  ]

  sbm_nfeatures: 20
  sbm_feature_mean: 0
  sbm_feature_variance: 1
  sbm_feature_sampling_variance: 30
  
  ood: LOC
  ood_loc_remove_edges: True
  ood_loc_num_classes: 1
  
training:
  ood_eval_during_training: False