from .gat.gat import GAT
from .gat.mcd_gat import MCD_GAT
from .gat.ensemble_gat import ENSEMBLE_GAT
from .gat.p_gat import P_GAT
from .gcn.gcn import GCN
from .gcn.mcd_gcn import MCD_GCN
from .gcn.ensemble_gcn import ENSEMBLE_GCN
from .gcn.p_gcn import P_GCN
from .ppnp.ppnp import PPNP
from .ppnp.mcd_ppnp import MCD_PPNP
from .ppnp.ensemble_ppnp import ENSEMBLE_PPNP
from .ppnp.p_ppnp import P_PPNP
from .gpn.gpn import GPN
from .mlp import MLP