custom_name: active_learning
tags: ['active_learning_cora_h1_v1']

experiment:

  seeds:
    end: 6
  iterations_per_seed: 3

  dataset: CORA_ML
  datapoints_training_per_class: 50
  datapoints_stopping: 300
  datapoints_known: 1500
  num_classes: 7
  
  sbm_nfeatures: 10
  sbm_feature_mean: 0
  sbm_feature_variance: 1
  sbm_feature_sampling_variance: 10
  
  active_learning: True
  active_learning_start_cap_per_class: 5
  active_learning_update_interval: 50
  active_learning_budget_per_update: 5
  active_learning_budget: 50
  active_learning_starting_class: [0]
  active_learning_selector: UNCERTAINTY
  active_learning_selector_network_mode: ISOLATED
  active_learning_selector_uncertainty_mode: ALEATORIC
  active_learning_l2_distance_logging: True

  ood: NONE
  
training:
  ood_eval_during_training: False
  patience: 
    TRAINING: 1000